import React, { useEffect, useState, useMemo } from 'react';
import * as THREE from 'three';
import { useLoader, useFrame } from '@react-three/fiber';
import { Html } from '@react-three/drei';
import { STLLoader, mergeBufferGeometries } from 'three-stdlib';
import { useProject } from '../contexts/ProjectContext';

interface CADGeometryProps {
    fileUrl: string;
    extension: string;
    isExploded?: boolean;
    explodeDistance?: number;
}

const useOCCTWorker = (fileUrl: string, extension: string) => {
    const [parts, setParts] = useState<{geometry: THREE.BufferGeometry, name: string, color: number[], constraint?: string}[] | null>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!['step', 'stp', 'iges', 'igs'].includes(extension)) return;

        const worker = new Worker(new URL('../workers/occt.worker.ts', import.meta.url), { type: 'module' });
        
        let active = true;

        const load = async () => {
            try {
                const response = await fetch(fileUrl);
                const buffer = await response.arrayBuffer();
                worker.postMessage({ buffer, extension, id: fileUrl });
            } catch (err: any) {
                if (active) setError(err.message);
            }
        };

        worker.onmessage = (e) => {
            if (!active) return;
            const { type, meshes, message } = e.data;
            if (type === 'SUCCESS') {
                const parsedParts: {geometry: THREE.BufferGeometry, name: string, color: number[], constraint?: string}[] = [];
                meshes.forEach((m: any) => {
                    if (!m.positions || m.positions.length === 0) return;
                    try {
                        const geometry = new THREE.BufferGeometry();
                        geometry.setAttribute('position', new THREE.BufferAttribute(m.positions, 3));
                        if (m.normals && m.normals.length === m.positions.length) {
                             geometry.setAttribute('normal', new THREE.BufferAttribute(m.normals, 3));
                        } else {
                             geometry.computeVertexNormals();
                        }
                        if (m.indices && m.indices.length > 0) {
                            geometry.setIndex(new THREE.BufferAttribute(m.indices, 1));
                        }
                        parsedParts.push({ geometry, name: m.name, color: m.color, constraint: m.constraint });
                    } catch (e) {
                         console.warn("Failed to construct buffer segment", e);
                    }
                });
                
                if (parsedParts.length === 0) {
                     setError("Zero valid geometry sectors generated by Kernel.");
                } else {
                     setParts(parsedParts);
                }
            } else {
                setError(message);
            }
        };

        worker.onerror = (err) => {
            if (active) setError(err.message);
        };

        load();

        return () => {
            active = false;
            worker.terminate();
        };
    }, [fileUrl, extension]);

    return { parts, error };
};

const STLUriLoader = ({ fileUrl }: { fileUrl: string }) => {
    const loadedGeom = useLoader(STLLoader, fileUrl);
    
    const processedGeometry = useMemo(() => {
        if (!loadedGeom) return null;
        const geom = loadedGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [loadedGeom]);

    if (!processedGeometry) return null;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLLegacyLoader = ({ rawPayload }: { rawPayload: string }) => {
    const [asyncGeom, setAsyncGeom] = useState<THREE.BufferGeometry | null>(null);

    useEffect(() => {
        if (rawPayload) {
            try {
                const loader = new STLLoader();
                const geom = loader.parse(rawPayload);
                setAsyncGeom(geom);
            } catch (err) {
                console.error("Legacy string STL parse failed:", err);
            }
        }
    }, [rawPayload]);

    const processedGeometry = useMemo(() => {
        if (!asyncGeom) return null;
        const geom = asyncGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [asyncGeom]);

    if (!processedGeometry) return null;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLAsyncLoader = ({ fileUrl }: { fileUrl: string }) => {
    const [asyncGeom, setAsyncGeom] = useState<THREE.BufferGeometry | null>(null);

    useEffect(() => {
        let active = true;
        fetch(fileUrl)
            .then(res => res.arrayBuffer())
            .then(buffer => {
                if (!active) return;
                try {
                    const loader = new STLLoader();
                    const geom = loader.parse(buffer);
                    setAsyncGeom(geom);
                } catch (e) {
                    console.error("Async STL ArrayBuffer parsing failed:", e);
                }
            })
            .catch(err => {
                if (active) console.error("Failed to fetch STL data URI:", err);
            });
        return () => { active = false; };
    }, [fileUrl]);

    const processedGeometry = useMemo(() => {
        if (!asyncGeom) return null;
        const geom = asyncGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [asyncGeom]);

    if (!processedGeometry) return <boxGeometry args={[0.001, 0.001, 0.001]} />;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLViewer = ({ fileUrl, rawPayload }: { fileUrl: string, rawPayload?: string }) => {
    const isUri = fileUrl.startsWith('blob:') || fileUrl.startsWith('http') || fileUrl.startsWith('data:');
    const isDataUri = fileUrl.startsWith('data:');
    
    return (
        <React.Suspense fallback={<boxGeometry args={[0.001, 0.001, 0.001]} />}>
            {isUri ? (
                isDataUri ? <STLAsyncLoader fileUrl={fileUrl} /> : <STLUriLoader fileUrl={fileUrl} />
            ) : (
                <STLLegacyLoader rawPayload={rawPayload || fileUrl} />
            )}
        </React.Suspense>
    );
};

const OCCTViewer = ({ fileUrl, extension, isExploded, explodeDistance }: { fileUrl: string, extension: string, isExploded?: boolean, explodeDistance?: number }) => {
    const { parts, error } = useOCCTWorker(fileUrl, extension);
    const { updateProjectField, activeProjectId, projects } = useProject();
    const activeProject = projects.find(p => p.id === activeProjectId);

    const [userMode, setUserMode] = useState<string | null>(null);

    useEffect(() => {
        if (parts && parts.length > 0 && activeProjectId) {
            const existingBOMMap = new Map();
            if (activeProject?.specs?.bom) {
                activeProject.specs.bom.forEach((b: any) => existingBOMMap.set(b.component, b));
            }

            let changed = false;
            const bom = parts.map(p => {
                const existing = existingBOMMap.get(p.name);
                if (!existing) changed = true;
                return {
                    component: p.name,
                    type: p.constraint ? `Mechanical (${p.constraint.toUpperCase()} joint)` : 'Structural',
                    quantity: 1,
                    estimatedCost: existing?.estimatedCost || "N/A",
                    color: existing?.color,
                    materialType: existing?.materialType
                };
            });
            
            if (changed || parts.length !== activeProject?.specs?.bom?.length) {
                updateProjectField(activeProjectId, 'specs.bom', bom);
            }
        }
    }, [parts, activeProjectId]); // Removed updateProjectField and activeProject from deps to prevent loop

    const { scaleFactor, centerOffset, optimalMode, partCenters } = useMemo(() => {
        if (!parts || parts.length === 0) return { scaleFactor: 1, centerOffset: new THREE.Vector3(), optimalMode: 'spherical', partCenters: [] };
        
        try {
            const box = new THREE.Box3();
            const centers: THREE.Vector3[] = [];
            
            parts.forEach(p => {
                p.geometry.computeBoundingBox();
                box.union(p.geometry.boundingBox!);
                centers.push(p.geometry.boundingBox!.getCenter(new THREE.Vector3()));
            });
            
            const size = box.max.clone().sub(box.min);
            const center = box.getCenter(new THREE.Vector3());
            const maxDimension = Math.max(size.x, size.y, size.z);
            let scale = 1;

            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    scale = scaleTarget / maxDimension;
                }
            }
            
            let opt = 'spherical';
            if (size.x > size.y * 1.8 && size.x > size.z * 1.8) opt = 'linear-x';
            else if (size.y > size.x * 1.8 && size.y > size.z * 1.8) opt = 'linear-y';
            else if (size.z > size.x * 1.8 && size.z > size.y * 1.8) opt = 'linear-z';
            
            const offset = center.clone().multiplyScalar(-1);
            return { scaleFactor: scale, centerOffset: offset, optimalMode: opt, partCenters: centers };
            
        } catch(e) {
            console.error("Geometry integration failed:", e);
        }
        return { scaleFactor: 1, centerOffset: new THREE.Vector3(), optimalMode: 'spherical', partCenters: [] };
    }, [parts]);

    useEffect(() => {
        const handleCycle = () => {
             const modes = ['spherical', 'linear-x', 'linear-y', 'linear-z'];
             setUserMode(prev => {
                 const current = prev || optimalMode;
                 const next = modes[(modes.indexOf(current) + 1) % modes.length];
                 console.log("Cycling Explosion Mode to:", next);
                 return next;
             });
        };
        window.addEventListener('cycle-explosion-mode', handleCycle);
        return () => window.removeEventListener('cycle-explosion-mode', handleCycle);
    }, [optimalMode]);

    const activeMode = userMode || optimalMode;
    const groupRef = React.useRef<THREE.Group>(null);

    useFrame(() => {
        if (!groupRef.current || !parts || parts.length === 0) return;
        const targetMultiplier = isExploded ? 1.0 : 0; 

        groupRef.current.children.forEach((mesh, idx) => {
             const pc = partCenters[idx];
             if (!pc) return;
             const assemblyCenter = centerOffset.clone().multiplyScalar(-1);
             const dirVector = pc.clone().sub(assemblyCenter);
             
             if (activeMode === 'linear-x') { dirVector.y = 0; dirVector.z = 0; }
             else if (activeMode === 'linear-y') { dirVector.x = 0; dirVector.z = 0; }
             else if (activeMode === 'linear-z') { dirVector.x = 0; dirVector.y = 0; }
             
             // The object's overall max dimension provides a baseline for the explosion spread.
             // explodeProgress goes from 0 to 1. 0 = assembled. 1 = max exploded.
             // maxSpread is a multiple of the assembly's bounding box to ensure clear separation.
             const explodeProgress = (explodeDistance !== undefined ? explodeDistance : 60) / 100;
             const maxSpread = Math.max(10, (1.5 / scaleFactor)); // proportional max reach
             
             // Explosion amount is proportional to the part's original distance from the center
             const targetPos = dirVector.clone().multiplyScalar(targetMultiplier * explodeProgress * maxSpread);
             mesh.position.lerp(targetPos, 0.08); // Spring-like easing over frames
        });
    });

    if (error) {
        console.error("OCCT Error:", error);
        return <boxGeometry args={[10, 10, 10]} />; 
    }

    if (!parts || parts.length === 0) {
        return (
            <Html center zIndexRange={[100, 0]}>
                 <div className="flex flex-col items-center gap-3 bg-black/90 backdrop-blur-md border border-blue-500/40 p-4 rounded-xl shadow-[0_0_30px_rgba(59,130,246,0.15)] pointer-events-none w-[240px]">
                     <div className="w-8 h-8 border-[3px] border-blue-500/20 border-t-blue-500 rounded-full animate-spin"></div>
                     <div className="text-blue-400 font-bold tracking-wider uppercase text-[9px] text-center">Parsing Assembly B-Rep<br/><span className="text-zinc-500 text-[8px] mt-1 block lowercase tracking-normal">Translating topological surfaces</span></div>
                 </div>
            </Html>
        );
    }

    const getPartColor = (p: any) => {
        if (activeProject?.specs?.bom) {
            const b = activeProject.specs.bom.find((item: any) => item.component === p.name);
            if (b && b.color) {
                return new THREE.Color(b.color);
            }
        }
        return new THREE.Color(...p.color);
    };

    return (
        <group scale={scaleFactor}>
            {isExploded && (
                <Html prepend center transform scale={1/scaleFactor} position={[0, -25, 0]}>
                    <div className="bg-orange-500 text-black px-2 py-0.5 rounded text-[8px] font-bold uppercase tracking-widest shadow-lg shadow-orange-500/20 opacity-80 backdrop-blur pointer-events-none">
                        Mode: {activeMode.replace('-', ' ')}
                    </div>
                </Html>
            )}
            <group position={centerOffset} ref={groupRef}>
                {parts.map((p, i) => (
                    <mesh key={i} geometry={p.geometry}>
                        <meshStandardMaterial color={getPartColor(p)} roughness={0.4} metalness={0.6} />
                    </mesh>
                ))}
            </group>
        </group>
    );
};


export const ImportedCADGeometry: React.FC<CADGeometryProps> = ({ fileUrl, extension, isExploded, explodeDistance }) => {
    let effectiveExtension = extension.toLowerCase();
    if (effectiveExtension === 'stl' && fileUrl && fileUrl.includes('firebasestorage')) {
        const urlLower = fileUrl.toLowerCase();
        if (urlLower.includes('.step') || urlLower.includes('.stp')) effectiveExtension = 'step';
        else if (urlLower.includes('.iges') || urlLower.includes('.igs')) effectiveExtension = 'iges';
        else if (urlLower.includes('.dxf')) effectiveExtension = 'dxf';
        else if (urlLower.includes('.obj')) effectiveExtension = 'obj';
    }

    const isSTL = ['stl', 'obj'].includes(effectiveExtension); 

    const isLegacyString = !fileUrl.startsWith('blob:') && !fileUrl.startsWith('http') && !fileUrl.startsWith('data:');

    const safeUrl = useMemo(() => {
        if (!fileUrl) return '';
        if (!isLegacyString) return fileUrl;

        if (fileUrl.length > 500000 && !fileUrl.trim().startsWith('solid ') && !fileUrl.trim().startsWith('ISO-10303')) {
        }

        return 'legacy-string';
    }, [fileUrl, isLegacyString]);
    
    if (!safeUrl && !isLegacyString) return null;

    if (safeUrl === 'CORRUPTED') {
        return (
            <mesh>
                <boxGeometry args={[15, 15, 15]} />
                <meshStandardMaterial color="#ef4444" wireframe />
            </mesh>
        );
    }

    if (isSTL) {
        return <STLViewer fileUrl={safeUrl} rawPayload={isLegacyString ? fileUrl : undefined} />;
    } else {
        return <OCCTViewer fileUrl={safeUrl} extension={effectiveExtension} isExploded={isExploded} explodeDistance={explodeDistance} />;
    }
};
