import React, { useEffect, useState, useMemo } from 'react';
import * as THREE from 'three';
import { useLoader } from '@react-three/fiber';
import { STLLoader, mergeBufferGeometries } from 'three-stdlib';

interface CADGeometryProps {
    fileUrl: string;
    extension: string;
}

const useOCCTWorker = (fileUrl: string, extension: string) => {
    const [geometries, setGeometries] = useState<THREE.BufferGeometry[] | null>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!['step', 'stp', 'iges', 'igs'].includes(extension)) return;

        const worker = new Worker(new URL('../workers/occt.worker.ts', import.meta.url), { type: 'module' });
        
        let active = true;

        const load = async () => {
            try {
                const response = await fetch(fileUrl);
                const buffer = await response.arrayBuffer();
                worker.postMessage({ buffer, extension, id: fileUrl });
            } catch (err: any) {
                if (active) setError(err.message);
            }
        };

        worker.onmessage = (e) => {
            if (!active) return;
            const { type, meshes, message } = e.data;
            if (type === 'SUCCESS') {
                const parsedGeoms: THREE.BufferGeometry[] = [];
                meshes.forEach((m: any) => {
                    if (!m.positions || m.positions.length === 0) return;
                    try {
                        const geometry = new THREE.BufferGeometry();
                        geometry.setAttribute('position', new THREE.BufferAttribute(m.positions, 3));
                        if (m.normals && m.normals.length === m.positions.length) {
                             geometry.setAttribute('normal', new THREE.BufferAttribute(m.normals, 3));
                        } else {
                             geometry.computeVertexNormals();
                        }
                        if (m.indices && m.indices.length > 0) {
                            geometry.setIndex(new THREE.BufferAttribute(m.indices, 1));
                        }
                        parsedGeoms.push(geometry);
                    } catch (e) {
                         console.warn("Failed to construct buffer segment", e);
                    }
                });
                
                if (parsedGeoms.length === 0) {
                     setError("Zero valid geometry sectors generated by Kernel.");
                } else {
                     setGeometries(parsedGeoms);
                }
            } else {
                setError(message);
            }
        };

        worker.onerror = (err) => {
            if (active) setError(err.message);
        };

        load();

        return () => {
            active = false;
            worker.terminate();
        };
    }, [fileUrl, extension]);

    return { geometries, error };
};

const STLUriLoader = ({ fileUrl }: { fileUrl: string }) => {
    const loadedGeom = useLoader(STLLoader, fileUrl);
    
    const processedGeometry = useMemo(() => {
        if (!loadedGeom) return null;
        const geom = loadedGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [loadedGeom]);

    if (!processedGeometry) return null;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLLegacyLoader = ({ rawPayload }: { rawPayload: string }) => {
    const [asyncGeom, setAsyncGeom] = useState<THREE.BufferGeometry | null>(null);

    useEffect(() => {
        if (rawPayload) {
            try {
                const loader = new STLLoader();
                const geom = loader.parse(rawPayload);
                setAsyncGeom(geom);
            } catch (err) {
                console.error("Legacy string STL parse failed:", err);
            }
        }
    }, [rawPayload]);

    const processedGeometry = useMemo(() => {
        if (!asyncGeom) return null;
        const geom = asyncGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [asyncGeom]);

    if (!processedGeometry) return null;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLAsyncLoader = ({ fileUrl }: { fileUrl: string }) => {
    const [asyncGeom, setAsyncGeom] = useState<THREE.BufferGeometry | null>(null);

    useEffect(() => {
        let active = true;
        fetch(fileUrl)
            .then(res => res.arrayBuffer())
            .then(buffer => {
                if (!active) return;
                try {
                    const loader = new STLLoader();
                    const geom = loader.parse(buffer);
                    setAsyncGeom(geom);
                } catch (e) {
                    console.error("Async STL ArrayBuffer parsing failed:", e);
                }
            })
            .catch(err => {
                if (active) console.error("Failed to fetch STL data URI:", err);
            });
        return () => { active = false; };
    }, [fileUrl]);

    const processedGeometry = useMemo(() => {
        if (!asyncGeom) return null;
        const geom = asyncGeom.clone();
        if (!geom.hasAttribute('normal')) geom.computeVertexNormals();
        
        geom.computeBoundingBox();
        const bbox = geom.boundingBox;
        if (bbox) {
            const size = bbox.max.clone().sub(bbox.min);
            const maxDimension = Math.max(size.x, size.y, size.z);
            if (maxDimension > 0) {
                const scaleTarget = 50; 
                if (maxDimension > 200 || maxDimension < 1) {
                    const scaleFactor = scaleTarget / maxDimension;
                    geom.scale(scaleFactor, scaleFactor, scaleFactor);
                }
            }
        }
        geom.center(); 
        return geom;
    }, [asyncGeom]);

    if (!processedGeometry) return <boxGeometry args={[0.001, 0.001, 0.001]} />;
    return <primitive object={processedGeometry} attach="geometry" />;
};

const STLViewer = ({ fileUrl, rawPayload }: { fileUrl: string, rawPayload?: string }) => {
    const isUri = fileUrl.startsWith('blob:') || fileUrl.startsWith('http') || fileUrl.startsWith('data:');
    const isDataUri = fileUrl.startsWith('data:');
    
    return (
        <React.Suspense fallback={<boxGeometry args={[0.001, 0.001, 0.001]} />}>
            {isUri ? (
                isDataUri ? <STLAsyncLoader fileUrl={fileUrl} /> : <STLUriLoader fileUrl={fileUrl} />
            ) : (
                <STLLegacyLoader rawPayload={rawPayload || fileUrl} />
            )}
        </React.Suspense>
    );
};

const OCCTViewer = ({ fileUrl, extension }: { fileUrl: string, extension: string }) => {
    const { geometries, error } = useOCCTWorker(fileUrl, extension);

    const mergedGeometry = useMemo(() => {
        if (!geometries || geometries.length === 0) return null;
        
        try {
            const merged = mergeBufferGeometries(geometries, false);
            if (merged && merged.attributes && merged.attributes.position) {
                merged.computeBoundingBox();
                const bbox = merged.boundingBox;
                if (bbox) {
                    const size = bbox.max.clone().sub(bbox.min);
                    const maxDimension = Math.max(size.x, size.y, size.z);
                    if (maxDimension > 0) {
                        const scaleTarget = 50; 
                        if (maxDimension > 200 || maxDimension < 1) {
                            const scaleFactor = scaleTarget / maxDimension;
                            merged.scale(scaleFactor, scaleFactor, scaleFactor);
                        }
                    }
                }
                merged.center();
                return merged;
            }
        } catch(e) {
            console.error("Geometry integration failed:", e);
        }
        return null;
    }, [geometries]);

    if (error) {
        console.error("OCCT Error:", error);
        return <boxGeometry args={[10, 10, 10]} />; 
    }

    if (!mergedGeometry) {
        return <boxGeometry args={[0.001, 0.001, 0.001]} />;
    }

    return <primitive object={mergedGeometry} attach="geometry" />;
};


export const ImportedCADGeometry: React.FC<CADGeometryProps> = ({ fileUrl, extension }) => {
    let effectiveExtension = extension.toLowerCase();
    if (effectiveExtension === 'stl' && fileUrl && fileUrl.includes('firebasestorage')) {
        const urlLower = fileUrl.toLowerCase();
        if (urlLower.includes('.step') || urlLower.includes('.stp')) effectiveExtension = 'step';
        else if (urlLower.includes('.iges') || urlLower.includes('.igs')) effectiveExtension = 'iges';
        else if (urlLower.includes('.dxf')) effectiveExtension = 'dxf';
        else if (urlLower.includes('.obj')) effectiveExtension = 'obj';
    }

    const isSTL = ['stl', 'obj'].includes(effectiveExtension); 

    const isLegacyString = !fileUrl.startsWith('blob:') && !fileUrl.startsWith('http') && !fileUrl.startsWith('data:');

    const safeUrl = useMemo(() => {
        if (!fileUrl) return '';
        if (!isLegacyString) return fileUrl;

        if (fileUrl.length > 500000 && !fileUrl.trim().startsWith('solid ') && !fileUrl.trim().startsWith('ISO-10303')) {
        }

        return 'legacy-string';
    }, [fileUrl, isLegacyString]);
    
    if (!safeUrl && !isLegacyString) return null;

    if (safeUrl === 'CORRUPTED') {
        return (
            <mesh>
                <boxGeometry args={[15, 15, 15]} />
                <meshStandardMaterial color="#ef4444" wireframe />
            </mesh>
        );
    }

    if (isSTL) {
        return <STLViewer fileUrl={safeUrl} rawPayload={isLegacyString ? fileUrl : undefined} />;
    } else {
        return <OCCTViewer fileUrl={safeUrl} extension={effectiveExtension} />;
    }
};
